### ISSUE TITLE
Wrong roles for party with id: "76" in release.json

### ISSUE THREAD

**Issue by pablissimo77** [ColinMaudry/tunisia-ocds-sample#6]
It should be roles: ["tenderer", "supplier"] instead roles: ["buyer"]

I suggest то use the following roles: ["buyer", "supplier", "tenderer", "enquirer"]

supplier - who signed contract with buyer
tenderer - who submit a bid
enquirer - who has made an enquiry

**Comment by ColinMaudry** [comment]
Can you please do a Pull request? That will be easier for me to have the change released.

**Comment by pablissimo77** [comment]
For this you need to give me the permission to access this repository.

**Comment by ColinMaudry** [comment]
I fixed it, thanks for flagging it.

**Comment by ColinMaudry** [comment]
You can do Pull Requests on public repositories by

- forking the repo
- creating a pull request here: https://github.com/ColinMaudry/tunisia-ocds-sample/compare

**Comment by pablissimo77** [comment]
Oh, great! I didn't Pull Requests on public repositories before :) Thank you!
